# Replace with the actual channel (non-public)
foretold_channel: SECRET

start_date: 2020-03-20 # ISO format

# Root directory of gleamviz (needs to contain data/sims)
gleamviz_dir: ~/GLEAMviz/

# Dir for intermediate and output files
output_dir: out/

# The generated defs are a product of scenarios and mitigations
# param_seasonalityAlphaMin - minmal activity in season
# param_occupancyRate - air travel percentage

scenarios:
  - param_seasonalityAlphaMin: 0.85
    param_occupancyRate: 70  # Note this is in percent!
    name: Weak seasonality<br>Weak reduction in air travel 
    color: "#edcdab"
  - param_seasonalityAlphaMin: 0.7
    param_occupancyRate: 70  # Note this is in percent!
    name: Medium seasonality<br>Weak reduction in air travel 
    color: "#edb77e"
  - param_seasonalityAlphaMin: 0.5
    param_occupancyRate: 70  # Note this is in percent!
    name: Strong seasonality<br>Weak reduction in air travel 
    color: "#e97f0f"
  - param_seasonalityAlphaMin: 0.85
    param_occupancyRate: 20  # Note this is in percent!
    name: Weak seasonality<br>Strong reduction in air travel 
    color: "#9ac9d9"
  - param_seasonalityAlphaMin: 0.7
    param_occupancyRate: 20  # Note this is in percent!
    name: Medium seasonality<br>Strong reduction in air travel 
    color: "#5abbdb"
  - param_seasonalityAlphaMin: 0.5
    param_occupancyRate: 20  # Note this is in percent!
    name: Strong seasonality<br>Strong reduction in air travel 
    color: "#007ca6"
  
mitigations:
  - param_beta: 1.285
    label: "None"
  - param_beta: 1.156 # 90%
    label: "Low"
  - param_beta: 1.028 # 80%
    label: "Medium"
  - param_beta: 0.899 # 70%
    label: "High"
  
# Use keys from regions.yaml
regions:
  - australia
  - czech republic
  - dubai
  - egypt
  - france
  - germany
  - hong kong city
  - india
  - indonesia
  - iran
  - italy
  - japan
  - netherlands
  - russia
  - singapore
  - south korea
  - spain
  - switzerland
  - united states
  - united kingdom

# How to assign estimate into compartments
compartments_mult:
  Infectious: 1.0  ## TODO: Ignored for now
  Exposed: 1.3     ## TODO: Only this is supported
