name: covid

on: [push]

env:
  IMAGE_NAME: covid

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
        args: "**.py --check"

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.8
    - run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry install
        poetry run pytest tests
